### ISSUE TITLE
Please remove this

### ISSUE THREAD

**Issue by objecthuman** [ankurgajurel/dynamic-subdomains-next#1]
https://github.com/ankurgajurel/dynamic-subdomains-next/blob/71cb83b5c312fd686c01a221948c7a9f2bc3eab8/app/page.tsx#L4

**Comment by ankurgajurel** [comment]
https://github.com/ankurgajurel/dynamic-subdomains-next/commit/3a5d88f344bb8b3e10e4f3a6bcbac4591317f7a8
